<?php

//Prevents the file from being accesssed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if(!class_exists('R8_Button_Generator')) {
	
	class R8_Button_Generator {
		
		function __construct() {
			
			self::define_constants();
			self::load_hooks();
			
		}
		
		public static function define_constants() {
			
			if(!defined('R8_IS_ADMIN')){
				define('R8_IS_ADMIN', is_admin());
			}
			
			if(!defined('R8_CURRENT_PAGE')) {
				define('R8_CURRENT_PAGE', basename($_SERVER['PHP_SELF']));
			}
			
			define( 'PLUGIN_PATH', plugins_url( '/', __FILE__ ) );
			define('WP_BUTTON_GENERATOR_PLUGIN_NAME', 'wp_button_generator');
			
		}
		
		public static function load_hooks() {
			
			//adding Button Shortcode
			add_action( 'plugins_loaded', array(__CLASS__, 'create_button_shortcode' ));
			
			//adding "Add Button" button on top of wysiwyg
            add_action( 'media_buttons', array(__CLASS__, 'add_button_button' ), 21);
            
            add_action( 'admin_menu', array(__CLASS__, 'add_settings_page' ));
            
            add_action( 'admin_init', array(__CLASS__, 'register_settings') );
            
            if(self::page_supports_add_button_button()){
                add_action( 'admin_footer',  array(__CLASS__, 'add_mce_popup' ));
            }
            
            add_action( 'admin_post_update_button_settings', array( __CLASS__, 'update_button_settings' ) );
			
		}
		
		public static function add_settings_page() {
			add_submenu_page( 'red8-functionality-plugin', 'WP Button Generator', 'Button Generator', 'manage_options', WP_BUTTON_GENERATOR_PLUGIN_NAME, array(__CLASS__, 'button_generator_options_page'));
			
		}
		
		public static function register_settings() {
			
			register_setting( 'wp_button_generator', 'default_bg_color' );
			register_setting( 'wp_button_generator', 'default_text_color' );
			register_setting( 'wp_button_generator', 'default_alignment' );
			register_setting( 'wp_button_generator', 'default_padding_top-bottom' );
			register_setting( 'wp_button_generator', 'default_padding_left-right' );
		}
		
		public static function button_generator_options_page() {
			
			include 'templates/options-page.php';
			
			wp_enqueue_script( 'colorpicker-js', PLUGIN_PATH . 'colorpicker/js/colorpicker.js', array('jquery'), '', true );
			wp_enqueue_script( 'colorpicker-eye', PLUGIN_PATH . 'colorpicker/js/eye.js', array('jquery'), '', true );
			wp_enqueue_script( 'colorpicker-utils', PLUGIN_PATH . 'colorpicker/js/utils.js', array('jquery'), '', true );
			wp_enqueue_script( 'colorpicker-layout', PLUGIN_PATH . 'colorpicker/js/layout.js', array('jquery'), '', true );
			wp_enqueue_style( 'colorpicker-css', PLUGIN_PATH . 'colorpicker/css/colorpicker.css' );
			
		}
		
		public static function update_button_settings() {
			
			if($_POST['default_bg_color']) {
				$defaultBGColor = $_POST['default_bg_color'];
			}
			
			if($_POST['default_text_color']) {
				$defaultTextColor = $_POST['default_text_color'];
			}
			
			if($_POST['default_padding_top-bottom']) {
				$defaultPaddingTopBottom = $_POST['default_padding_top-bottom'];
			}
			
			if($_POST['default_padding_left-right']) {
				$defaultPaddingLeftRight = $_POST['default_padding_left-right'];
			}
			
			if($_POST['default_alignment']) {
				$defaultButtonAlignment = $_POST['default_alignment'];
			}
			
			if($_POST['default_border_radius']) {
				$defaultBorderRadius = $_POST['default_border_radius'];
			}
			
			update_option( 'default_bg_color', $defaultBGColor );
			update_option( 'default_text_color', $defaultTextColor );
			update_option( 'default_padding_top-bottom', $defaultPaddingTopBottom );
			update_option( 'default_padding_left-right', $defaultPaddingLeftRight );
			update_option( 'default_alignment', $defaultButtonAlignment );
			update_option( 'default_border_radius', $defaultBorderRadius );
			
			wp_redirect( get_admin_url() . 'admin.php?page='.WP_BUTTON_GENERATOR_PLUGIN_NAME.'&updated=true' );
			exit();
			
		}
		
		//Adds button shortcode to be generated by options
		public static function create_button_shortcode() {
			
			function add_button_shortcode($atts, $content=null) {
				extract(shortcode_atts(array(
					'link' => 'null',
					'background_color' => 'null',
					'text_color' => 'null',
					'target' => 'null',
					'padding' => 'null',
					'alignment' => 'null',
					'border_radius' => 'null'
				), $atts));
					
				return "<div class=\"wp_button_generator_button\" style=\"text-align: $alignment;\"><a href='$link' " . $target . "style='border-radius: $border_radius; background-color: $background_color; color: $text_color; padding: $padding; text-decoration: none; display: inline-block;'" . ">" . $content . "</a></div>";
				
			}
			
			if( shortcode_exists( 'add_button_shortcode' ) ) {
				return;
			} else {
				add_shortcode( 'button', 'add_button_shortcode' );
			}
		}
		
		//Checks if the page is a new or existing post/page page
		public static function page_supports_add_button_button() {
	        $is_post_edit_page = in_array(R8_CURRENT_PAGE, array('post.php', 'page.php', 'page-new.php', 'post-new.php'));
	
	        $display_add_button_button = apply_filters("display_add_button_button", $is_post_edit_page);
	
	        return $display_add_button_button;
	    }
	    
	    
	    //Adds button above wysiwyg if it is supported
	    public static function add_button_button() {

	        $is_add_button_page = self::page_supports_add_button_button();
	        if(!$is_add_button_page)
	            return;
	
	            // display button matching new UI
	            echo '<style>
	                    .wp-core-ui a.add_button_button{
	                     padding-left: 0.4em;
	                    }
	                 </style>
	                  <a href="#TB_inline?width=480&height=1000&inlineId=select_button_attributes" class="thickbox button add_button_button" id="add_button" title="' . __("Add Button", 'button_generator') . '"><span class="dashicons dashicons-admin-settings"></span> ' . __("Add Button", "button_generator") . '</a>';
	      
	    }
	    
	    //Adds modal for button options
	    public static function add_mce_popup() {
		    
		    include 'templates/generator-modal.php';
		    	
			wp_enqueue_script( 'colorpicker-js', PLUGIN_PATH . 'colorpicker/js/colorpicker.js', array('jquery'), '', true );
			wp_enqueue_style( 'colorpicker-css', PLUGIN_PATH . 'colorpicker/css/colorpicker.css' );
				
	    }
		
		
	} // End class R8_Button_Generator
	
	$R8_Button_Generator = new R8_Button_Generator();
	
} // End class exists check